services:
  - type: web
    name: techguard-back
    env: node
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
