services:
  - type: web
    name: techguard-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: PYTHON_PATH
        value: python3
      - key: NODE_ENV
        value: production
    runtime:
      node: 22
      python: 3.10

